IsDevSystem=false
Port = 9002

CORSHosts = [
	"https://demoadmin.lumenshine.com",    
	"http://localhost:8000",	
	"http://localhost:8001",
	"http://localhost:8002",
	"http://localhost:8003"
]

[AdminDB]
    DBUser = "icop"
    DBPassword = "xxxx"
    DBHost = "localhost"
    DBPort = 5433
    DBName = "admin"

[CustomerDB]
    DBUser = "icop"
    DBPassword = "xxxx"
    DBHost = "localhost"
    DBPort = 5433
    DBName = "icop"
