IsDevSystem = false
Port = "9003"

CORSHosts = [
	"https://admin.lumenshine.com",	
	"https://demo.lumenshine.com",	
	"https://api.lumenshine.com",

	"http://localhost:8000",	
	"http://localhost:8001",
	"http://localhost:8002",
	"http://localhost:8003"
]

LocalDownloadDir = "downloads/"
HorizonURL = "https://horizon.stellar.org/" #used for ticker. must end in /
[DB]
    DBUser = "icop"
    DBPassword = "xxxx"
    DBHost = "localhost"
    DBPort = 5433
    DBName = "chart"
    # DBSchema = "public"

[Ticker]
    TickSeconds = 60
    SourceCurrency = "XLM"
    DestinationCurrency = [ "USD", "BTC", "ETH", "EUR", "CNY", "KRW" ]
    DecentralizedExchangeCode = [ "MOBI", "CNY", "RMT"]
    DecentralizedExchangeIssuer = [ "xxxx", "xxx", "xxx"]

[Cleanup]
    CleanupMinutesInterval= 60
    HoursToKeepMinutelyData = 24
	HoursToKeepHourlyData   = 720