version: '3.6'

services:
  
  stellar:
    # in order to run this container you must do a 'docker-compose.exe run stellar' to run the image in interactive mode
    # this will create the database. You must specify a pwd for the db
    # when setting up this image, you have to empty the stellar-config directory, in order to force the db creation
    stdin_open: true
    tty: true
    # build:
    #  context: ./stellar
    restart: "no"
    image: stellar/quickstart
    volumes:
      - stellar-data:/opt/stellar/postgresql/data        
      - ./stellar-config:/opt/stellar           
      
    command: --testnet    
    ports:
      - "5434:5432"
      - "8000:8000"
      - "11625:11625"
      - "11626:11626"
  
  #this setup is used for the stellar service: friendbot, foundationserver   
  stellaraddons:
    build:
      context: .
      dockerfile: DockerfileStellarAddons
      
    #volumes:      
    #  - .\stellaraddons-config:/stellaraddons-config       
      
# please create the data volumes external with this command
# docker volume create --name stellar-data -d local
volumes:
  stellar-data:
    external: true
